version: '3.8'

# API检测器 Docker Compose 配置
# 使用requirements.txt管理Python依赖

services:
  api-detector:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-detector
    container_name: api-detector
    restart: unless-stopped
    ports:
      - "18000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - APP_ENV=production
      - DEBUG=false
      - RELOAD=false
      - HOST=0.0.0.0
      - PORT=8000
      # 你可以在这里覆盖其他环境变量
      # - GITHUB_TOKEN=your_token
      # - API_KEY=your_api_key 