name: api-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - fastapi>=0.100.0
  - uvicorn>=0.22.0
  - pydantic>=2.0.0
  - httpx>=0.24.0
  - python-multipart>=0.0.6
  - aiofiles>=23.1.0
  - gitpython>=3.1.32
  - pytest>=7.3.1
  - pytest-asyncio>=0.21.0
  - black>=23.3.0
  - isort>=5.12.0
  - mypy>=1.3.0
  - pylint>=2.17.4
  - pip:
    - grpcio-tools>=1.54.2
    - graphql-core>=3.2.3
    - openapi-spec-validator>=0.5.7
    - websockets>=11.0.3 